### ISSUE TITLE
[turbo_yandex] Закрытие тега `header`

### ISSUE THREAD

**Issue by russsiq** [irbees2008/Plugins-NGCMS#1]
https://github.com/irbees2008/Plugins-NGCMS/blob/eb6b0aa6c77008b8d30c3e27be3115fc54737968/turbo_yandex/turbo_yandex.php#L130

Я синтаксиса турбо-страниц не знаю, но тем не менее, вот эта строка вызывает сомнения: почему-то тег закрывается только при наличии условий?

**Comment by irbees2008** [comment]
инструкция https://yandex.ru/dev/turbo/doc/rss/markup-docpage/   не знаю ,делал  от балды, чтобы у меня работало,и работает

**Comment by russsiq** [comment]
https://github.com/irbees2008/turbo_yandex
